export const Pages = {
  Login : "LoginPage",
  Dashboard : "DashboardPage",
  FindPatient: "FindPatientPage",
  RegisterPatient : "RegisterPatientPage",
  EditPatient : "EditPatientPage",
  PatientDetails: "PatientDetailsPage",
  ViewRegimes: "ViewRegimesPage",
  ModifyRegime: "CreateRegimePage",
  CreateRegime: "CreateRegimePage",
  DischargePatient: "DischargePatientPage",
  FindExercise: "FindExercisePage",
  ViewProgress: "ViewProgressPage",
  ReviewExercise: "ReviewExercisePage",
  ForgotPassword: "ForgotPasswordPage",
  ResetPassword: "ResetPasswordPage",
  EditMyDetails: "EditMyDetailsPage",
  PatientDashboard: "PatientDashboardPage",
  PatientRegimes: "PatientRegimesPage",
  ViewExercise: "ViewExercisePage",
  ViewFeedback: "ViewFeedbackPage",

};
